### ISSUE TITLE
Android crashes with: Didn't find class "java.util.Base64"

### ISSUE THREAD

**Issue by atlascoder** [WalletConnect/react-native-simple-crypto#21]
```
Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
        at android.os.Looper.loop(Looper.java:154) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226) 
        at java.lang.Thread.run(Thread.java:762) 
     Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Ljava/util/Base64;
        at com.pedrouid.crypto.RCTAes.encrypt(RCTAes.java:129)
        at com.pedrouid.crypto.RCTAes.encrypt(RCTAes.java:66)
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372) 
        at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:151) 
        at com.facebook.react.bridge.queue.NativeRunnable.run(Native Method) 
        at android.os.Handler.handleCallback(Handler.java:751) 
        at android.os.Handler.dispatchMessage(Handler.java:95) 
        at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27) 
        at android.os.Looper.loop(Looper.java:154) 
        at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226) 
        at java.lang.Thread.run(Thread.java:762) 
     Caused by: java.lang.ClassNotFoundException: Didn't find class "java.util.Base64" on path: DexPathList[[zip file "/data/app/XXXXXXX/base.apk"],nativeLibraryDirectories=[/data/app/XXXXXXX/lib/arm, /data/app/XXXXXXX/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib]]
```

**Comment by ghbutton** [comment]
https://github.com/ghbutton/react-native-simple-crypto/pull/22

**Comment by ghbutton** [comment]
Should be fixed, please test with the latest version

**Comment by atlascoder** [comment]
thanks!
